In [2]:
#스마트폰이나 스피커, 앱 같은 형태로 보급되는 인공지능이 갖춰여하는 필수 능력은 사람의 언어를 이해하는 것이다
#이러한 능력을 '자연어처리(Natural Language Processing, NLP)'이다
#자연어란 우리가 평소에 말하는 음성이나 텍스트를 말한다
#즉, 자연어처리는 이러한 음성이나 텍스트를 컴퓨터가 인식하고 처리하는 것이다
#컴퓨터는 수치로 된 데이터만 이해하므로 텍스트자료 그대로를 딥러닝에 적용하기는 불가능하다
#따라서 텍스트를 정제하는 전처리 과정이 꼭 필요하다

### 텍스트의 토큰화

In [3]:
#먼저해야 할 일은 텍스트를 잘게 나누는 것이다
#입력할 텍스트가 준비된다면 이를 단어별, 문장별, 형태소별로 나눌 수 있는데, 이렇게 작게 나누어진 하나의 단위를 토큰(token)이라한다
#입력된 텍스트를 잘게 나누는 과정을 토큰화라고 한다

In [4]:
print('해보지 않으면 해낼 수 없다')

해보지 않으면 해낼 수 없다


In [5]:
#케라스가 제공하는 text 모듈의 text_to_word_sequence() 함수를 사용하면 문장을 단어 단위로 쉽게 나눌 수 있다
#해당 함수를 불러와 전처리할 텍스트를 지정한 후, 다음과 같이 토큰화한다

In [6]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text = '해보지 않으면 해낼 수 없다'
result = text_to_word_sequence(text)
print(result)

['해보지', '않으면', '해낼', '수', '없다']


In [7]:
#이렇게 주어진 텍스트를 단어 단위로 쪼개고 각 단어가 몇 번이나 중복해서 쓰였는지를 알 수 있다
#단어의 빈도수를 알면 텍스트에서 중요한 역할을 하는 단어를 파악할 수 있다
#따라서 텍스트를 단어 단위로 쪼개는 것은 가장 많이 쓰이는 전처리 과정이다
#이러한 전처리 방법을 Bag-of-Words라고 한다
#단어의 가방이라는 말 뜻 그대로, 같은 단어끼리 따로따로 가방에 담은 뒤 각 가방에 몇 개의 단어가 들어있는지를 세는 기법이다
#케라스의 Tokenizer() 함수를 사용하면 단어의 빈도 수를 쉽게 계산할 수 있다

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [13]:
#토큰화함수인 Tokenizer()를 이용해 전처리 해보자

In [16]:
token = Tokenizer() #토큰화 함수 지정
token.fit_on_texts(docs) #토큰화 함수에 문장 적용
print(token.word_counts) #단어의 빈도 수를 계산한 결과 출력

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer 
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.', 
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.', 
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.'] 
token = Tokenizer() # 토큰화 함수 지정 
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용 
print(token.word_counts) # 단어의 빈도 수를 계산한 결과 출력

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [17]:
#총 몇개의 문장이 들어있는지를 셀 수 있다

In [18]:
print(token.document_count)

3


In [19]:
#word_docs() 함수를 통해 각 단어들이 몇개의 문장에 나오는 가를 세어서 출력할 수도 있다
#출력되는 순서는 랜덤이다

In [21]:
print(token.word_docs)

defaultdict(<class 'int'>, {'각': 1, '텍스트의': 2, '나누어': 1, '토큰화': 3, '먼저': 1, '합니다': 1, '단어를': 1, '해야': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '수': 1, '결과는': 1, '사용할': 1, '한': 1, '있습니다': 1})


In [22]:
#각 단어에 매겨진 인덱스 값을 출력하려면 word_index() 함수를 사용하면 됩니다

In [23]:
print(token.word_index)

{'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


#### - 코드 정리

In [8]:
#텍스트 전처리 함수 text_to_word_sequence() 호출
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [9]:
#전처리 할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'

In [14]:
#해당 텍스트 토큰화
result = text_to_word_sequence(text)
print('\n원문:\n', text)
print('\n토큰화\n', result)


원문:
 해보지 않으면 해낼 수 없다

토큰화
 ['해보지', '않으면', '해낼', '수', '없다']


In [15]:
#텍스트 전처리 함수 Tokenizer() 호출
from tensorflow.keras.preprocessing.text import Tokenizer

In [24]:
#전처리하려는 3개의 문장 정하기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
        '토큰화 한 결과는 딥러닝에서 사용할 수 있습니다.'
       ]

In [25]:
#토큰화 함수를 이용해 전처리하는 과정
token = Tokenizer() #토큰화 함수 지정
token.fit_on_texts(docs) #토큰화 함수에 문장 적용하기

In [26]:
#각 옵션에 맞춰 단어의 빈도 수를 계산한 결과 출력
print('\n단어 카운트:\n', token.word_counts)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [27]:
#출력되는 순서는 랜덤
print('\n문장 카운트:', token.document_count)
print('\n각 단어가 몇개의 문장에 포함되어 있는가:\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값:\n', token.word_index)


문장 카운트: 3

각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'각': 1, '텍스트의': 2, '나누어': 1, '토큰화': 3, '먼저': 1, '합니다': 1, '단어를': 1, '해야': 1, '인식됩니다': 1, '단어로': 1, '딥러닝에서': 2, '수': 1, '결과는': 1, '사용할': 1, '한': 1, '있습니다': 1})

각 단어에 매겨진 인덱스 값:
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


### 단어의 원-핫 인코딩

In [1]:
#앞서 우리는 문장을 컴퓨터가 알아들을 수 있게 토큰화하고 단어의 빈도수를 확인해 보았다
#하지만 단순히 단어의 출현 빈도만 가지고는 해당 단어가 문장의 어디에서 왔는지, 각 단어의 순서는 어떠했는지에 관한 정보를 얻을 수 없다
#단어가 문장의 다른 요소와 어떤 관계를 가지고 있는지를 알아보는 방법이 필요하다
#이러한 기법 중에서 가장 기본적인 방법인 원-핫인코딩
#각 단어를 모두 0으로 바꾸고 원하는 단어만 1로 바꾸는 것이 원-핫 인코딩
#파이썬의 배열은 인덱스가 0부터 시작하므로 맨 앞에 0이 추가되는것에 주의

In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [3]:
#이제 각 단어를 원-핫인코딩 방식으로 표현해보자
#text_to_sequences() 함수를 사용해서 앞서 만들어진 토큰의 인덱스로만 채워진 새로운 배열을 만들어보자

In [10]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [11]:
#이제 1~6까지의 정수로 인덱스 되어 있는것을 0과 1로만 이루어진 배열로 바꿔주는 to_categorical() 함수를 사용해 원-핫인코딩 진행
#배열 맨 앞에 0이 추가되므로 단어 수보다 1이 더 많게 인덱스 숫자를 잡아주는 것에 유의

In [12]:
from keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


### 단어 임베딩

In [13]:
#원-핫 인코딩을 그대로 사용하면 벡터의 길이가 너무 길어지는 단점이 존재한다
#예를들어 1만개의 단어 토큰으로 이루어진 말뭉치를 다룬다고 할때, 이 데이터를 원-핫인코딩으로 벡터화하면 
#9,999개의 0과 1로 이루어진 단어 벡터를 1만개나 만들어야 한다
#이러한 공간적 낭비를 해결하기 위해 등장한 것이 단어 임베딩(word embedding)이다.

In [14]:
#단어 임베딩을 주어진 배열을 정해진 길이로 압축시킨다.
#단어 임베딩으로 얻은 결과는 밀집된 정보를 가지고 있고 공간의 낭비가 적어진다
#이런 결과가 가능한 이유는 각 단어 간의 유사도를 계산했기 때문이다
#예를들어 happy라는 단어는 bad보다 good에 가깝고, cat이라는 단어는 good보다 dog에 가깝다는것을 고려하여 각 배열을 새로운 수치고 바꿔줌
#이러한 단어 간의 유사도는 오차역전파의 개념으로 설명된다
#적절한 크기로 배열을 바꾸어 주기 위해 최적의 유사도를 계산하는 학습과정을 거치는 것이다
#이 과정은 케라스의 Embedding() 함수를 사용하면 가능

In [15]:
from keras.models import Sequential
from keras.layers import Embedding

model = Sequential()
model.add(Embedding(16,4))

In [17]:
#Embedding이라는 함수는 최소 2개의 매개변수를 필요로하는데 바로 입력과 출력의 크기이다
#Embedding(16,4)는 입력될 총 단어 수는 16, 임베딩 후 출력되는 벡터 크기는 4로 하겠다는 뜻이다
#Embedding(16,4, input_length=2)라면 총 입력되는 단어 수는 16개 이지만 매번 2개씩만 넣겠다는 뜻

### 텍스트를 읽고 긍정, 부정 예측하기

In [1]:
#영화를 보고 남긴 리뷰를 딥러닝 모델로 학습해서 각 리뷰가 긍정적인지 부정적인지를 예측해보자
#짧은 리뷰 10개를 불러와 각각 긍정이면 1이라는 클래스를, 부정적이면 0이라는 클래스로 지정하자

In [22]:
from numpy import array
#텍스트리뷰자료지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다',
        '한번 더 보고싶네요', '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

#긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [23]:
#토큰화 과정을 진행한다

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [25]:
#토큰에 지정된 인덱스로 새로운 배열을 생성한다
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [26]:
#주어진 텍스트는 숫자로 이루어진 배열로 재편된다
#각 단어가 1부터 20까지의 숫자로 토큰화되었다는 것을 알 수 있다
#그런데 입력된 리뷰 데이터의 토큰 수가 각각 다르다는 것에 유의
#딥러닝 모델에 입력을 하려면 학습 데이터의 길이가 동일해야 한다
#이처럼 길이를 똑같이 맞춰 주는 작업을 패딩(padding)과정이라고 한다
#패딩을 자연어처리뿐만 아니라 GAN에서도 중요한 역할을 한다

In [28]:
#패딩 작업을 위해 케라스는 pad_sequence() 함수를 제공한다
#pad_sequence() 함수를 사용하면 원하는 길이보다 짧은 부분은 숫자0을 넣어서 채워주고, 긴데이터는 잘라서 같은 길이로 맞춘다
#앞서 생성한 x배열을 4개의 길이로 맞춰보자

In [32]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x,4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [33]:
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력해 보자
#임베딩 함수에 필요한 세가지 parameter는 '입력, 출력, 단어수'이다
#총 몇개의 단어 집합에서(입력), 몇 개의 임베딩 결과를 사용할 것인지(출력), 그리고 매번 입력될 단어의 수는 몇개로 할건지(단어수)를 정함
#먼저 총 몇개의 단어가 입력되어야 하는지를 정해보자
#전체 단어의 맨 앞에 0이 먼저 나와야 하므로 총 단어 수에 1을 더해야 한다

In [34]:
word_size = len(token.word_index) + 1

In [35]:
#이제 몇개의 임베딩 결과를 사용할 것인지, 즉 출력을 정해야 한다
#이번 예제에서는 word_size 만큼의 입력 값을 이용해 8개의 임베딩 결과를 만들어 보자
#여기서 8이라는 숫자는 임의로 정한것이다. 데이터에 따라 적절한 값으로 바꿀 수 있다
#이때 만들어진 8개의 임베딩 결과는 우리 눈에 보이지 않는다
#내부에서 계산하여 딥러닝의 레이어로 활용한다
#끝으로 매번 입력된 단어수는 패딩 과정을 거쳐 4개의 길이로 맞춰줬으므로 4개의 단어가 들어가게 설정한다

In [36]:
from tensorflow.keras.layers import Embedding
Embedding(word_size, 8, input_length=4)

In [37]:
#이를 이용해 모델을 만들어보자

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print('\n Accuracy: %.4f' %(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6873 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6856 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6839 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 996us/step - loss: 0.6822 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6805 - accuracy: 0.6000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6788 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6771 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 995us/step - loss: 0.6754 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6737 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6719 - accuracy: 0.9000
Epoch 11/20
1/1 [==================

#### - 코드정리

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

import numpy as np
import tensorflow as tf
from numpy import array

In [42]:
#텍스트리뷰자료지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다',
        '한번 더 보고싶네요', '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

#긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [43]:
#토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로에요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [44]:
#토큰에 지정된 인덱스로 새로운 배열을 생성한다
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [45]:
#패딩, 서로다른 길이를 4로 맞춤
padded_x = pad_sequences(x, 4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [46]:
#임베딩에 입력될 단어 수 지정
word_size = len(token.word_index) + 1
print(word_size)

21


In [48]:
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print('\n Accuracy: %.4f' %(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 996us/step - loss: 0.6975 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6952 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6906 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6883 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6861 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6838 - accuracy: 0.7000
Epoch 8/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6816 - accuracy: 0.7000
Epoch 9/20
1/1 [==============================] - 0s 990us/step - loss: 0.6793 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6771 - accuracy: 0.7000
Epoch 11/20
1/1 [==================